version: '3.4'
services:
  smartengine:
    image: smartengine
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3000
    depends_on:
      - mongo
    networks:
      - db
  mongo:
    image: mongo:latest
    container_name: 'nest_mongo'
    restart: always
    volumes:
      - mongodb_data_container:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nest
    ports:
      - 27000:27017
    networks:
      - db
networks:
  db:
volumes:
  mongodb_data_container:
