version: '3.4'
services:
  redisservice:
    image: redis:4.0.11
    ports:
      - 7010:6379
    command: '--requirepass testredis'
    volumes:
      - redis_data:/data
    networks:
      - db
  smartengine:
    image: smartengine
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3000
    depends_on:
      - dbservice
      - redisservice
    networks:
      - db
  dbservice:
    image: mongo:latest
    container_name: 'mongodbservice'
    restart: always
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27000:27017
    networks:
      - db
networks:
  db:
volumes:
  mongodb_data_container:
  redis_data:
