version: '3.4'
services:
  smartengine:
    image: smartengine
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: 'nest_mongo'
    volumes:
      - mongodb_data_container:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nest
    ports:
      - 27017:27017
networks:
  webnet:
volumes:
  mongodb_data_container:
